
/* tslint:disable */
import {Category} from '../enums/category.enum';

export function getSources (category: Category) {
    return sourceData().filter(item => item.category === category);
}

interface Source {
    id: string;
    name: string;
    description: string;
    url: string;
    category: Category;
    language: string;
    country: string;
}


function sourceData (): any[] {

  return  [
            // { id: 'abc-news',
            // name: 'ABC News',
            // description: 'Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.',
            // url: 'http://abcnews.go.com',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            // { id: 'al-jazeera-english',
            // name: 'Al Jazeera English',
            // description: 'News, analysis from the Middle East and worldwide, multimedia and interactives, opinions, documentaries, podcasts, long reads and broadcast schedule.',
            // url: 'http://www.aljazeera.com',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            // { id: 'associated-press',
            // name: 'Associated Press',
            // description: 'The AP delivers in-depth coverage on the international, politics, lifestyle, business, and entertainment news.',
            // url: 'https://apnews.com/',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            { id: 'axios',
            name: 'Axios',
            description: 'Axios are a new media company delivering vital, trustworthy news and analysis in the most efficient, illuminating and shareable ways possible.',
            url: 'https://www.axios.com',
            category: Category.General,
            language: 'en',
            country: 'us' },

            // { id: 'breitbart-news',
            // name: 'Breitbart News',
            // description: 'Syndicated news and opinion website providing continuously updated headlines to top news and analysis sources.',
            // url: 'http://www.breitbart.com',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            { id: 'bbc-news',
            name: 'BBC News',
            description: '',
            url: 'http://www.bbc.co.uk',
            category: Category.General,
            language: 'en',
            country: 'us' },

            { id: 'cbc-news',
            name: 'CBC News',
            description: 'CBC News is the division of the Canadian Broadcasting Corporation responsible for the news gathering and production of news programs on the corporation\'s English-language operations, namely CBC Television, CBC Radio, CBC News Network, and CBC.ca.',
            url: 'http://www.cbc.ca',
            category: Category.General,
            language: 'en',
            country: 'ca' },


            // { id: 'cbs-news',
            // name: 'CBS News',
            // description: 'CBS News: dedicated to providing the best in journalism under standards it pioneered at the dawn of radio and television and continue in the digital age.',
            // url: 'http://www.cbsnews.com',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            // { id: 'cnn',
            // name: 'CNN',
            // description: 'View the latest news and breaking news today for U.S., world, weather, entertainment, politics and health at CNN',
            // url: 'http://us.cnn.com',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            // { id: 'fox-news',
            // name: 'Fox News',
            // description: 'Breaking News, Latest News and Current News from FOXNews.com. Breaking news and video. Latest Current News: U.S., World, Entertainment, Health, Business, Technology, Politics, Sports.',
            // url: 'http://www.foxnews.com',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            // { id: 'google-news',
            // name: 'Google News',
            // description: 'Comprehensive, up-to-date news coverage, aggregated from sources all over the world by Google News.',
            // url: 'https://news.google.com',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            // { id: 'msnbc',
            // name: 'MSNBC',
            // description: 'Breaking news and in-depth analysis of the headlines, as well as commentary and informed perspectives from The Rachel Maddow Show, Morning Joe & more.',
            // url: 'http://www.msnbc.com',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            // { id: 'national-review',
            // name: 'National Review',
            // description: 'National Review: Conservative News, Opinion, Politics, Policy, & Current Events.',
            // url: 'https://www.nationalreview.com/',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            // { id: 'nbc-news',
            // name: 'NBC News',
            // description: 'Breaking news, videos, and the latest top stories in world news, business, politics, health and pop culture.',
            // url: 'http://www.nbcnews.com',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            // { id: 'newsweek',
            // name: 'Newsweek',
            // description: 'Newsweek provides in-depth analysis, news and opinion about international issues, technology, business, culture and politics.',
            // url: 'http://www.newsweek.com',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            { id: 'new-york-magazine',
            name: 'New York Magazine',
            description: 'NYMAG and New York magazine cover the new, the undiscovered, the next in politics, culture, food, fashion, and behavior nationally, through a New York lens.',
            url: 'http://nymag.com',
            category: Category.General,
            language: 'en',
            country: 'us' },

            { id: 'politico',
            name: 'Politico',
            description: 'Political news about Congress, the White House, campaigns, lobbyists and issues.',
            url: 'https://www.politico.com',
            category: Category.General,
            language: 'en',
            country: 'us' },

            // { id: 'reddit-r-all',
            // name: 'Reddit /r/all',
            // description: 'Reddit is an entertainment, social news networking service, and news website. Reddit\'s registered community members can submit content, such as text posts or direct links.',
            // url: 'https://www.reddit.com/r/all',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            // { id: 'reuters',
            // name: 'Reuters',
            // description: 'Reuters.com brings you the latest news from around the world, covering breaking news in business, politics, entertainment, technology, video and pictures.',
            // url: 'http://www.reuters.com',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            // { id: 'the-american-conservative',
            // name: 'The American Conservative',
            // description: 'Realism and reform. A new voice for a new generation of conservatives.',
            // url: 'http://www.theamericanconservative.com/',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            // { id: 'the-hill',
            // name: 'The Hill',
            // description: 'The Hill is a top US political website, read by the White House and more lawmakers than any other site -- vital for policy, politics and election campaigns.',
            // url: 'http://thehill.com',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            // { id: 'the-huffington-post',
            // name: 'The Huffington Post',
            // description: 'The Huffington Post is a politically liberal American online news aggregator and blog that has both localized and international editions founded by Arianna Huffington, Kenneth Lerer, Andrew Breitbart, and Jonah Peretti, featuring columnists.',
            // url: 'http://www.huffingtonpost.com',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            { id: 'the-new-york-times',
            name: 'The New York Times',
            description: 'The New York Times: Find breaking news, multimedia, reviews & opinion on Washington, business, sports, movies, travel, books, jobs, education, real estate, cars & more at nytimes.com.',
            url: 'http://www.nytimes.com',
            category: Category.General,
            language: 'en',
            country: 'us' },

            { id: 'the-washington-post',
            name: 'The Washington Post',
            description: 'Breaking news and analysis on politics, business, world national news, entertainment more. In-depth DC, Virginia, Maryland news coverage including traffic, weather, crime, education, restaurant reviews and more.',
            url: 'https://www.washingtonpost.com',
            category: Category.General,
            language: 'en',
            country: 'us' },

            { id: 'the-washington-times',
            name: 'The Washington Times',
            description: 'The Washington Times delivers breaking news and commentary on the issues that affect the future of our nation.',
            url: 'https://www.washingtontimes.com/',
            category: Category.General,
            language: 'en',
            country: 'us' },

            // { id: 'time',
            // name: 'Time',
            // description: 'Breaking news and analysis from TIME.com. Politics, world news, photos, video, tech reviews, health, science and entertainment news.',
            // url: 'http://time.com',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            // { id: 'usa-today',
            // name: 'USA Today',
            // description: 'Get the latest national, international, and political news at USATODAY.com.',
            // url: 'http://www.usatoday.com/news',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            // { id: 'vice-news',
            // name: 'Vice News',
            // description: 'Vice News is Vice Media, Inc.\'s current affairs channel, producing daily documentary essays and video through its website and YouTube channel. It promotes itself on its coverage of \'under - reported stories\'.',
            // url: 'https://news.vice.com',
            // category: Category.General,
            // language: 'en',
            // country: 'us' },

            { id: 'national-geographic',
            name: 'National Geographic',
            description: 'Reporting our world daily: original nature and science news from National Geographic.',
            url: 'http://news.nationalgeographic.com',
            category: Category.Science,
            language: 'en',
            country: 'us' },

            { id: 'new-scientist',
            name: 'New Scientist',
            description: 'Breaking science and technology news from around the world. Exclusive stories and expert analysis on space, technology, health, physics, life and Earth.',
            url: 'https://www.newscientist.com/section/news',
            category: Category.Science,
            language: 'en',
            country: 'us' },

            { id: 'next-big-future',
            name: 'Next Big Future',
            description: 'Coverage of science and technology that have the potential for disruption, and analysis of plans, policies, and technology that enable radical improvement.',
            url: 'https://www.nextbigfuture.com',
            category: Category.Science,
            language: 'en',
            country: 'us' },

            { id: 'ars-technica',
            name: 'Ars Technica',
            description: 'The PC enthusiast\'s resource. Power users and the tools they love, without computing religion.',
            url: 'http://arstechnica.com',
            category: Category.Technology,
            language: 'en',
            country: 'us' },

            // { id: 'crypto-coins-news',
            // name: 'Crypto Coins News',
            // description: 'Providing breaking cryptocurrency news - focusing on Bitcoin, Ethereum, ICOs, blockchain technology, and smart contracts.',
            // url: 'https://www.ccn.com',
            // category: Category.Technology,
            // language: 'en',
            // country: 'us' },

            { id: 'engadget',
            name: 'Engadget',
            description: 'Engadget is a web magazine with obsessive daily coverage of everything new in gadgets and consumer electronics.',
            url: 'https://www.engadget.com',
            category: Category.Technology,
            language: 'en',
            country: 'us' },

            { id: 'hacker-news',
            name: 'Hacker News',
            description: 'Hacker News is a social news website focusing on computer science and entrepreneurship. It is run by Paul Graham\'s investment fund and startup incubator, Y Combinator. In general, content that can be submitted is defined as \'anything that gratifies one\'s intellectual curiosity\'.',
            url: 'https://news.ycombinator.com',
            category: Category.Technology,
            language: 'en',
            country: 'us' },

            { id: 'recode',
            name: 'Recode',
            description: 'Get the latest independent tech news, reviews and analysis from Recode with the most informed and respected journalists in technology and media.',
            url: 'http://www.recode.net',
            category: Category.Technology,
            language: 'en',
            country: 'us' },

            { id: 'techcrunch',
            name: 'TechCrunch',
            description: 'TechCrunch is a leading technology media property, dedicated to obsessively profiling startups, reviewing new Internet products, and breaking tech news.',
            url: 'https://techcrunch.com',
            category: Category.Technology,
            language: 'en',
            country: 'us' },

            { id: 'techradar',
            name: 'TechRadar',
            description: 'The latest technology news and reviews, covering computing, home entertainment systems, gadgets and more.',
            url: 'http://www.techradar.com',
            category: Category.Technology,
            language: 'en',
            country: 'us' },

            { id: 'the-next-web',
            name: 'The Next Web',
            description: 'The Next Web is one of the world’s largest online publications that delivers an international perspective on the latest news about Internet technology, business and culture.',
            url: 'http://thenextweb.com',
            category: Category.Technology,
            language: 'en',
            country: 'us' },

            { id: 'the-verge',
            name: 'The Verge',
            description: 'The Verge covers the intersection of technology, science, art, and culture.',
            url: 'http://www.theverge.com',
            category: Category.Technology,
            language: 'en',
            country: 'us' },

            { id: 'wired',
            name: 'Wired',
            description: 'Wired is a monthly American magazine, published in print and online editions, that focuses on how emerging technologies affect culture, the economy, and politics.',
            url: 'https://www.wired.com',
            category: Category.Technology,
            language: 'en',
            country: 'us' },

            { id: 'buzzfeed',
            name: 'Buzzfeed',
            description: 'BuzzFeed is a cross-platform, global network for news and entertainment that generates seven billion views each month.',
            url: 'https://www.buzzfeed.com',
            category: Category.Entertainment,
            language: 'en',
            country: 'us' },

            { id: 'entertainment-weekly',
            name: 'Entertainment Weekly',
            description: 'Online version of the print magazine includes entertainment news, interviews, reviews of music, film, TV and books, and a special area for magazine subscribers.',
            url: 'http://www.ew.com',
            category: Category.Entertainment,
            language: 'en',
            country: 'us' },

            { id: 'ign',
            name: 'IGN',
            description: 'IGN is your site for Xbox One, PS4, PC, Wii-U, Xbox 360, PS3, Wii, 3DS, PS Vita and iPhone games with expert reviews, news, previews, trailers, cheat codes, wiki guides and walkthroughs.',
            url: 'http://www.ign.com',
            category: Category.Entertainment,
            language: 'en',
            country: 'us' },

            { id: 'mashable',
            name: 'Mashable',
            description: 'Mashable is a global, multi-platform media and entertainment company.',
            url: 'http://mashable.com',
            category: Category.Entertainment,
            language: 'en',
            country: 'us' },

            { id: 'mtv-news',
            name: 'MTV News',
            description: 'The ultimate news source for music, celebrity, entertainment, movies, and current events on the web. It\'s pop culture on steroids.',
            url: 'http://www.mtv.com/news',
            category: Category.Entertainment,
            language: 'en',
            country: 'us' },

            { id: 'polygon',
            name: 'Polygon',
            description: 'Polygon is a gaming website in partnership with Vox Media. Our culture focused site covers games, their creators, the fans, trending stories and entertainment news.',
            url: 'http://www.polygon.com',
            category: Category.Entertainment,
            language: 'en',
            country: 'us' },

            { id: 'medical-news-today',
            name: 'Medical News Today',
            description: 'Medical news and health news headlines posted throughout the day, every day.',
            url: 'http://www.medicalnewstoday.com',
            category: 'health',
            language: 'en',
            country: 'us' },

            { id: 'bleacher-report',
            name: 'Bleacher Report',
            description: 'Sports journalists and bloggers covering NFL, MLB, NBA, NHL, MMA, college football and basketball, NASCAR, fantasy sports and more. News, photos, mock drafts, game scores, player profiles and more!',
            url: 'http://www.bleacherreport.com',
            category: Category.Sports,
            language: 'en',
            country: 'us' },

            { id: 'espn',
            name: 'ESPN',
            description: 'ESPN has up-to-the-minute sports news coverage, scores, highlights and commentary for NFL, MLB, NBA, College Football, NCAA Basketball and more.',
            url: 'http://espn.go.com',
            category: Category.Sports,
            language: 'en',
            country: 'us' },

            { id: 'espn-cric-info',
            name: 'ESPN Cric Info',
            description: 'ESPN Cricinfo provides the most comprehensive cricket coverage available including live ball-by-ball commentary, news, unparalleled statistics, quality editorial comment and analysis.',
            url: 'http://www.espncricinfo.com/',
            category: Category.Sports,
            language: 'en',
            country: 'us' },

            { id: 'fox-sports',
            name: 'Fox Sports',
            description: 'Find live scores, player and team news, videos, rumors, stats, standings, schedules and fantasy games on FOX Sports.',
            url: 'http://www.foxsports.com',
            category: Category.Sports,
            language: 'en',
            country: 'us' },

            { id: 'nfl-news',
            name: 'NFL News',
            description: 'The official source for NFL news, schedules, stats, scores and more.',
            url: 'http://www.nfl.com/news',
            category: Category.Sports,
            language: 'en',
            country: 'us' },

            { id: 'nhl-news',
            name: 'NHL News',
            description: 'The most up-to-date breaking hockey news from the official source including interviews, rumors, statistics and schedules.',
            url: 'https://www.nhl.com/news',
            category: Category.Sports,
            language: 'en',
            country: 'us' },

            {
                id:'australian-financial-review',
                name:'Australian Financial Review',
                description:'The Australian Financial Review reports the latest news from business, finance, investment and politics, updated in real time. It has a reputation for independent, award-winning journalism and is essential reading for the business and investor community.',
                url:'http://www.afr.com',
                category: Category.Business,
                language:'en',
                country:'au'
            },
            {  
                id: 'bloomberg',
                name: 'Bloomberg',
                description:'Bloomberg delivers business and markets news, data, analysis, and video to the world, featuring stories from Businessweek and Bloomberg News.',
                url:'http://www.bloomberg.com',
                category: Category.Business,
                language:'en',
                country:'us'
            },
            {  
                id:'business-insider',
                name:'Business Insider',
                description:'Business Insider is a fast-growing business site with deep financial, media, tech, and other industry verticals. Launched in 2007, the site is now the largest business news site on the web.',
                url:'http://www.businessinsider.com',
                category: Category.Business,
                language:'en',
                country:'us'
            },
            {  
                id:'business-insider-uk',
                name:'Business Insider (UK)',
                description:'Business Insider is a fast-growing business site with deep financial, media, tech, and other industry verticals. Launched in 2007, the site is now the largest business news site on the web.',
                url:'http://uk.businessinsider.com',
                category: Category.Business,
                language:'en',
                country:'gb'
            },
            {  
                id:'cnbc',
                name:'CNBC',
                description:'Get latest business news on stock markets, financial & earnings on CNBC. View world markets streaming charts & video; check stock tickers and quotes.',
                url:'http://www.cnbc.com',
                category: Category.Business,
                language:'en',
                country:'us'
            },
            {  
                id:'financial-post',
                name:'Financial Post',
                description:'Find the latest happenings in the Canadian Financial Sector and stay up to date with changing trends in Business Markets. Read trading and investing advice from professionals.',
                url:'http://business.financialpost.com',
                category: Category.Business,
                language:'en',
                country:'ca'
            },
            {  
                id:'financial-times',
                name:'Financial Times',
                description:'The latest UK and international business, finance, economic and political news, comment and analysis from the Financial Times on FT.com.',
                url:'http://www.ft.com/home/uk',
                category: Category.Business,
                language:'en',
                country:'gb'
            },
            {  
                id:'fortune',
                name:'Fortune',
                description:'Fortune 500 Daily and Breaking Business News',
                url:'http://fortune.com',
                category: Category.Business,
                language:'en',
                country:'us'
            },
            {  
                id:'the-economist',
                name:'The Economist',
                description:'The Economist offers authoritative insight and opinion on international news, politics, business, finance, science, technology and the connections between them.',
                url:'http://www.economist.com',
                category: Category.Business,
                language:'en',
                country:'gb'
            },
            {  
                id:'the-wall-street-journal',
                name:'The Wall Street Journal',
                description:'WSJ online coverage of breaking news and current headlines from the US and around the world. Top stories, photos, videos, detailed analysis and in-depth reporting.',
                url:'http://www.wsj.com',
                category: Category.Business,
                language:'en',
                country:'us'
            }
        ];
    }
